language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - echo 'deb http://repo.reverbrain.com/precise current/amd64/' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libcocaine-dev libboost-system-dev --force-yes
after_script:
  - npm run coveralls
